name: cargo-deny
on:
  push:
    paths:
      - .github/workflows/cargo-deny.yml
      - Cargo.toml
      - deny.toml

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          rust-version: 1.92
